# This is a basic workflow to help you get started with Actions

name: New CI

on:
  workflow_call:
    workflows: [CI Builds]
    types: [completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  aJob:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Dump GitHub context
      id: github_context_step
      run: echo $JSON
      env:
        JSON: ${{ toJSON(github) }}